
def autogenerated_warning():
    return """
// swift-format-ignore-file
//
// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################
"""


def upper_first(s):
    return s[:1].upper() + s[1:]


# Each primitive type maps to a concrete ConfigReader method.
#
# - name: The display name used in doc comments (e.g. "`Bool`", "`[String]`")
# - type: The Swift type used in signatures
# - reader_method: The ConfigReader method name (e.g. "bool", "stringArray")
primitive_types = [
    {"name": "Bool", "type": "Bool", "reader_method": "bool"},
    {"name": "[Bool]", "type": "[Bool]", "reader_method": "boolArray"},
    {"name": "Float64", "type": "Float64", "reader_method": "double"},
    {"name": "[Float64]", "type": "[Float64]", "reader_method": "doubleArray"},
    {"name": "Int", "type": "Int", "reader_method": "int"},
    {"name": "[Int]", "type": "[Int]", "reader_method": "intArray"},
    {"name": "String", "type": "String", "reader_method": "string"},
    {"name": "[String]", "type": "[String]", "reader_method": "stringArray"},
    {"name": "[UInt8]", "type": "[UInt8]", "reader_method": "bytes"},
    {"name": "[[UInt8]]", "type": "[[UInt8]]", "reader_method": "byteChunkArray"},
]


# String-convertible types use `reader.string(forKey:as:...)` and
# `reader.stringArray(forKey:as:...)`.
#
# - protocol: The Swift protocol constraint
# - doc_name: Display name for doc comments
string_convertible_types = [
    {"protocol": "RawRepresentable<String>", "doc_name": "RawRepresentable<String>"},
    {"protocol": "ExpressibleByConfigString", "doc_name": "ExpressibleByConfigString"},
]


# Int-convertible types use `reader.int(forKey:as:...)` and
# `reader.intArray(forKey:as:...)`.
#
# - protocol: The Swift protocol constraint
# - doc_name: Display name for doc comments
int_convertible_types = [
    {"protocol": "RawRepresentable<Int>", "doc_name": "RawRepresentable<Int>"},
    {"protocol": "ExpressibleByConfigInt", "doc_name": "ExpressibleByConfigInt"},
]
