//
//  ConfigVariableReader+FunctionsTests.swift
//  DevConfiguration
//
//  Generated using gyb.
//

// swift-format-ignore-file
//
// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################

import Configuration
import DevFoundation
import DevTesting
import Testing

@testable import DevConfiguration

struct ConfigVariableReader_FunctionsTests: RandomValueGenerating {
    var randomNumberGenerator = makeRandomNumberGenerator()

    /// A mutable provider for testing.
    let provider = MutableInMemoryProvider(initialValues: [:])

    /// The event bus for testing event posting.
    let eventBus = EventBus()

    /// The reader under test.
    lazy var reader: ConfigVariableReader = {
        ConfigVariableReader(providers: [provider], eventBus: eventBus)
    }()

    /// Sets a value in the provider for the given key with a random `isSecret` flag.
    private mutating func setProviderValue(_ content: ConfigContent, forKey key: ConfigKey) {
        provider.setValue(
            .init(content, isSecret: randomBool()),
            forKey: .init(key)
        )
    }


    // MARK: - Bool tests

    @Test
    mutating func valueForBoolReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = BoolTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BoolTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Bool>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForBoolReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = BoolTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<Bool>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForBoolReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = BoolTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BoolTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Bool>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForBoolReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = BoolTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<Bool>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForBoolReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = BoolTestValues.random(using: &randomNumberGenerator)
        let updatedValue = BoolTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = BoolTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Bool>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    BoolTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptBoolReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = BoolTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BoolTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Bool>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [Bool] tests

    @Test
    mutating func valueForBoolArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = BoolArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BoolArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Bool]>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForBoolArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = BoolArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[Bool]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForBoolArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = BoolArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BoolArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Bool]>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForBoolArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = BoolArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[Bool]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForBoolArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = BoolArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = BoolArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = BoolArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Bool]>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    BoolArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptBoolArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = BoolArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BoolArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Bool]>(key: key, defaultValue: defaultValue)
        setProviderValue(BoolArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - Float64 tests

    @Test
    mutating func valueForFloat64ReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = Float64TestValues.random(using: &randomNumberGenerator)
        let defaultValue = Float64TestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Float64>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64TestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForFloat64ReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = Float64TestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<Float64>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForFloat64ReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = Float64TestValues.random(using: &randomNumberGenerator)
        let defaultValue = Float64TestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Float64>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64TestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForFloat64ReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = Float64TestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<Float64>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForFloat64ReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = Float64TestValues.random(using: &randomNumberGenerator)
        let updatedValue = Float64TestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = Float64TestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Float64>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64TestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    Float64TestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptFloat64ReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = Float64TestValues.random(using: &randomNumberGenerator)
        let defaultValue = Float64TestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Float64>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64TestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [Float64] tests

    @Test
    mutating func valueForFloat64ArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = Float64ArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = Float64ArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Float64]>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64ArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForFloat64ArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = Float64ArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[Float64]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForFloat64ArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = Float64ArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = Float64ArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Float64]>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64ArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForFloat64ArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = Float64ArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[Float64]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForFloat64ArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = Float64ArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = Float64ArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = Float64ArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Float64]>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64ArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    Float64ArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptFloat64ArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = Float64ArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = Float64ArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Float64]>(key: key, defaultValue: defaultValue)
        setProviderValue(Float64ArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - Int tests

    @Test
    mutating func valueForIntReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = IntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = IntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Int>(key: key, defaultValue: defaultValue)
        setProviderValue(IntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForIntReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = IntTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<Int>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForIntReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = IntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = IntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Int>(key: key, defaultValue: defaultValue)
        setProviderValue(IntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForIntReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = IntTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<Int>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForIntReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = IntTestValues.random(using: &randomNumberGenerator)
        let updatedValue = IntTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = IntTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Int>(key: key, defaultValue: defaultValue)
        setProviderValue(IntTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    IntTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptIntReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = IntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = IntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<Int>(key: key, defaultValue: defaultValue)
        setProviderValue(IntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [Int] tests

    @Test
    mutating func valueForIntArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = IntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = IntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Int]>(key: key, defaultValue: defaultValue)
        setProviderValue(IntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForIntArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = IntArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[Int]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForIntArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = IntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = IntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Int]>(key: key, defaultValue: defaultValue)
        setProviderValue(IntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForIntArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = IntArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[Int]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForIntArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = IntArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = IntArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = IntArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Int]>(key: key, defaultValue: defaultValue)
        setProviderValue(IntArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    IntArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptIntArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = IntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = IntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[Int]>(key: key, defaultValue: defaultValue)
        setProviderValue(IntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - String tests

    @Test
    mutating func valueForStringReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = StringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = StringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<String>(key: key, defaultValue: defaultValue)
        setProviderValue(StringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForStringReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = StringTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<String>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForStringReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = StringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = StringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<String>(key: key, defaultValue: defaultValue)
        setProviderValue(StringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForStringReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = StringTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<String>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForStringReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = StringTestValues.random(using: &randomNumberGenerator)
        let updatedValue = StringTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = StringTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<String>(key: key, defaultValue: defaultValue)
        setProviderValue(StringTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    StringTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptStringReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = StringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = StringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<String>(key: key, defaultValue: defaultValue)
        setProviderValue(StringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [String] tests

    @Test
    mutating func valueForStringArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = StringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = StringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[String]>(key: key, defaultValue: defaultValue)
        setProviderValue(StringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForStringArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = StringArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[String]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForStringArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = StringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = StringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[String]>(key: key, defaultValue: defaultValue)
        setProviderValue(StringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForStringArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = StringArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[String]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForStringArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = StringArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = StringArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = StringArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[String]>(key: key, defaultValue: defaultValue)
        setProviderValue(StringArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    StringArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptStringArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = StringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = StringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[String]>(key: key, defaultValue: defaultValue)
        setProviderValue(StringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [UInt8] tests

    @Test
    mutating func valueForBytesReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = BytesTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BytesTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[UInt8]>(key: key, defaultValue: defaultValue)
        setProviderValue(BytesTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForBytesReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = BytesTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[UInt8]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForBytesReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = BytesTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BytesTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[UInt8]>(key: key, defaultValue: defaultValue)
        setProviderValue(BytesTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForBytesReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = BytesTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[UInt8]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForBytesReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = BytesTestValues.random(using: &randomNumberGenerator)
        let updatedValue = BytesTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = BytesTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[UInt8]>(key: key, defaultValue: defaultValue)
        setProviderValue(BytesTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    BytesTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptBytesReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = BytesTestValues.random(using: &randomNumberGenerator)
        let defaultValue = BytesTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[UInt8]>(key: key, defaultValue: defaultValue)
        setProviderValue(BytesTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [[UInt8]] tests

    @Test
    mutating func valueForByteChunkArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ByteChunkArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ByteChunkArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[[UInt8]]>(key: key, defaultValue: defaultValue)
        setProviderValue(ByteChunkArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForByteChunkArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = ByteChunkArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[[UInt8]]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForByteChunkArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = ByteChunkArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ByteChunkArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[[UInt8]]>(key: key, defaultValue: defaultValue)
        setProviderValue(ByteChunkArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForByteChunkArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = ByteChunkArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[[UInt8]]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForByteChunkArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = ByteChunkArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = ByteChunkArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = ByteChunkArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[[UInt8]]>(key: key, defaultValue: defaultValue)
        setProviderValue(ByteChunkArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    ByteChunkArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptByteChunkArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ByteChunkArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ByteChunkArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[[UInt8]]>(key: key, defaultValue: defaultValue)
        setProviderValue(ByteChunkArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - RawRepresentable<String> tests

    @Test
    mutating func valueForRawRepresentableStringReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableStringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockStringEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForRawRepresentableStringReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableStringTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockStringEnum>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableStringReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableStringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockStringEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableStringReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableStringTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockStringEnum>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForRawRepresentableStringReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = RawRepresentableStringTestValues.random(using: &randomNumberGenerator)
        let updatedValue = RawRepresentableStringTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockStringEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    RawRepresentableStringTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptRawRepresentableStringReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableStringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockStringEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [RawRepresentable<String>] tests

    @Test
    mutating func valueForRawRepresentableStringArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableStringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockStringEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForRawRepresentableStringArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableStringArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockStringEnum]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableStringArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableStringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockStringEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableStringArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableStringArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockStringEnum]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForRawRepresentableStringArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = RawRepresentableStringArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = RawRepresentableStringArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockStringEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    RawRepresentableStringArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptRawRepresentableStringArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableStringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableStringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockStringEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableStringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - ExpressibleByConfigString tests

    @Test
    mutating func valueForExpressibleByConfigStringReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigStringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigStringValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForExpressibleByConfigStringReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigStringTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigStringValue>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigStringReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigStringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigStringValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigStringReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigStringTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigStringValue>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForExpressibleByConfigStringReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = ExpressibleByConfigStringTestValues.random(using: &randomNumberGenerator)
        let updatedValue = ExpressibleByConfigStringTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigStringValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    ExpressibleByConfigStringTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptExpressibleByConfigStringReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigStringTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigStringValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [ExpressibleByConfigString] tests

    @Test
    mutating func valueForExpressibleByConfigStringArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigStringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigStringValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForExpressibleByConfigStringArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigStringArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigStringValue]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigStringArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigStringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigStringValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigStringArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigStringArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigStringValue]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForExpressibleByConfigStringArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = ExpressibleByConfigStringArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = ExpressibleByConfigStringArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigStringValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    ExpressibleByConfigStringArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptExpressibleByConfigStringArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigStringArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigStringArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigStringValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigStringArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - RawRepresentable<Int> tests

    @Test
    mutating func valueForRawRepresentableIntReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableIntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockIntEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForRawRepresentableIntReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableIntTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockIntEnum>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableIntReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableIntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockIntEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableIntReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableIntTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockIntEnum>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForRawRepresentableIntReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = RawRepresentableIntTestValues.random(using: &randomNumberGenerator)
        let updatedValue = RawRepresentableIntTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockIntEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    RawRepresentableIntTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptRawRepresentableIntReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableIntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockIntEnum>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [RawRepresentable<Int>] tests

    @Test
    mutating func valueForRawRepresentableIntArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableIntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockIntEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForRawRepresentableIntArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableIntArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockIntEnum]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableIntArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableIntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockIntEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForRawRepresentableIntArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = RawRepresentableIntArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockIntEnum]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForRawRepresentableIntArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = RawRepresentableIntArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = RawRepresentableIntArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockIntEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    RawRepresentableIntArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptRawRepresentableIntArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = RawRepresentableIntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = RawRepresentableIntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockIntEnum]>(key: key, defaultValue: defaultValue)
        setProviderValue(RawRepresentableIntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - ExpressibleByConfigInt tests

    @Test
    mutating func valueForExpressibleByConfigIntReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigIntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigIntValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForExpressibleByConfigIntReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigIntTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigIntValue>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigIntReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigIntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigIntValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigIntReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigIntTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigIntValue>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForExpressibleByConfigIntReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = ExpressibleByConfigIntTestValues.random(using: &randomNumberGenerator)
        let updatedValue = ExpressibleByConfigIntTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigIntValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    ExpressibleByConfigIntTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptExpressibleByConfigIntReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigIntTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<MockConfigIntValue>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - [ExpressibleByConfigInt] tests

    @Test
    mutating func valueForExpressibleByConfigIntArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigIntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigIntValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func valueForExpressibleByConfigIntArrayReturnsDefaultWhenKeyNotFound() {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigIntArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigIntValue]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = reader.value(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigIntArrayReturnsProviderValue() async throws {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigIntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigIntValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == expectedValue)
    }


    @Test
    mutating func fetchValueForExpressibleByConfigIntArrayReturnsDefaultWhenKeyNotFound() async throws {
        // set up
        let key = randomConfigKey()
        let defaultValue = ExpressibleByConfigIntArrayTestValues.random(using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigIntValue]>(key: key, defaultValue: defaultValue)

        // exercise
        let result = try await reader.fetchValue(for: variable)

        // expect
        #expect(result == defaultValue)
    }


    @Test
    mutating func watchValueForExpressibleByConfigIntArrayReceivesUpdates() async throws {
        // set up
        let key = randomConfigKey()
        let initialValue = ExpressibleByConfigIntArrayTestValues.random(using: &randomNumberGenerator)
        let updatedValue = ExpressibleByConfigIntArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntArrayTestValues.different(from: initialValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigIntValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntArrayTestValues.configContent(for: initialValue), forKey: key)

        // exercise and expect
        try await reader.watchValue(for: variable) { updates in
            var iterator = updates.makeAsyncIterator()

            let value1 = try await iterator.next()
            #expect(value1 == initialValue)

            provider.setValue(
                .init(
                    ExpressibleByConfigIntArrayTestValues.configContent(for: updatedValue),
                    isSecret: randomBool()
                ),
                forKey: .init(key)
            )

            let value2 = try await iterator.next()
            #expect(value2 == updatedValue)
        }
    }


    @Test
    mutating func subscriptExpressibleByConfigIntArrayReturnsProviderValue() {
        // set up
        let key = randomConfigKey()
        let expectedValue = ExpressibleByConfigIntArrayTestValues.random(using: &randomNumberGenerator)
        let defaultValue = ExpressibleByConfigIntArrayTestValues.different(from: expectedValue, using: &randomNumberGenerator)
        let variable = ConfigVariable<[MockConfigIntValue]>(key: key, defaultValue: defaultValue)
        setProviderValue(ExpressibleByConfigIntArrayTestValues.configContent(for: expectedValue), forKey: key)

        // exercise
        let result = reader[variable]

        // expect
        #expect(result == expectedValue)
    }


    // MARK: - Event Bus Integration

    @Test
    mutating func valuePostsAccessSucceededEventWhenFound() async throws {
        // set up
        let observer = ContextualBusEventObserver(context: ())
        eventBus.addObserver(observer)

        let key = randomConfigKey()
        let expectedValue = randomBool()
        let variable = ConfigVariable<Bool>(key: key, defaultValue: !expectedValue)
        provider.setValue(
            .init(
                .bool(expectedValue),
                isSecret: randomBool()
            ),
            forKey: .init(variable.key)
        )

        let (eventStream, continuation) = AsyncStream<ConfigVariableAccessSucceededEvent>.makeStream()
        observer.addHandler(for: ConfigVariableAccessSucceededEvent.self) { (event, _) in
            continuation.yield(event)
        }

        // exercise
        _ = reader.value(for: variable)

        // expect
        let postedEvent = try #require(await eventStream.first { _ in true })
        #expect(postedEvent.key == AbsoluteConfigKey(variable.key))
        #expect(postedEvent.value.content == .bool(expectedValue))
    }
}


// MARK: - Primitive TestValues

private enum BoolTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> Bool {
        Bool.random(using: &generator)
    }


    static func different(from value: Bool, using generator: inout some RandomNumberGenerator) -> Bool {
        !value
    }


    static func configContent(for value: Bool) -> ConfigContent {
        .bool(value)
    }
}


private enum BoolArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [Bool] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) { Bool.random(using: &generator) }
    }


    static func different(from value: [Bool], using generator: inout some RandomNumberGenerator) -> [Bool] {
        value + random(using: &generator)
    }


    static func configContent(for value: [Bool]) -> ConfigContent {
        .boolArray(value)
    }
}


private enum Float64TestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> Float64 {
        Float64.random(in: 1 ... 100_000, using: &generator)
    }


    static func different(from value: Float64, using generator: inout some RandomNumberGenerator) -> Float64 {
        value + random(using: &generator)
    }


    static func configContent(for value: Float64) -> ConfigContent {
        .double(value)
    }
}


private enum Float64ArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [Float64] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) { Float64.random(in: 1 ... 100_000, using: &generator) }
    }


    static func different(from value: [Float64], using generator: inout some RandomNumberGenerator) -> [Float64] {
        value + random(using: &generator)
    }


    static func configContent(for value: [Float64]) -> ConfigContent {
        .doubleArray(value)
    }
}


private enum IntTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> Int {
        Int.random(in: 1 ... 100_000, using: &generator)
    }


    static func different(from value: Int, using generator: inout some RandomNumberGenerator) -> Int {
        value + random(using: &generator)
    }


    static func configContent(for value: Int) -> ConfigContent {
        .int(value)
    }
}


private enum IntArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [Int] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) { Int.random(in: 1 ... 100_000, using: &generator) }
    }


    static func different(from value: [Int], using generator: inout some RandomNumberGenerator) -> [Int] {
        value + random(using: &generator)
    }


    static func configContent(for value: [Int]) -> ConfigContent {
        .intArray(value)
    }
}


private enum StringTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> String {
        let count = Int.random(in: 5 ... 20, using: &generator)
        return String.randomAlphanumeric(count: count, using: &generator)
    }


    static func different(from value: String, using generator: inout some RandomNumberGenerator) -> String {
        value + random(using: &generator)
    }


    static func configContent(for value: String) -> ConfigContent {
        .string(value)
    }
}


private enum StringArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [String] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) { String.randomAlphanumeric(count: count * 3, using: &generator) }
    }


    static func different(from value: [String], using generator: inout some RandomNumberGenerator) -> [String] {
        value + random(using: &generator)
    }


    static func configContent(for value: [String]) -> ConfigContent {
        .stringArray(value)
    }
}


private enum BytesTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [UInt8] {
        let count = Int.random(in: 1 ... 32, using: &generator)
        return Array(count: count) { UInt8.random(in: .min ... .max, using: &generator) }
    }


    static func different(from value: [UInt8], using generator: inout some RandomNumberGenerator) -> [UInt8] {
        value + random(using: &generator)
    }


    static func configContent(for value: [UInt8]) -> ConfigContent {
        .bytes(value)
    }
}


private enum ByteChunkArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [[UInt8]] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) {
            let byteCount = Int.random(in: 1 ... 32, using: &generator)
            return Array(count: byteCount) { UInt8.random(in: .min ... .max, using: &generator) }
        }
    }


    static func different(from value: [[UInt8]], using generator: inout some RandomNumberGenerator) -> [[UInt8]] {
        value + random(using: &generator)
    }


    static func configContent(for value: [[UInt8]]) -> ConfigContent {
        .byteChunkArray(value)
    }
}



// MARK: - MockStringEnum

private enum MockStringEnum: String, CaseIterable, Sendable {
    case alpha
    case bravo
    case charlie
    case delta
}


// MARK: - MockConfigStringValue

private struct MockConfigStringValue: ExpressibleByConfigString, Hashable, Sendable {
    let stringValue: String

    var description: String { stringValue }

    init?(configString: String) {
        self.stringValue = configString
    }
}


// MARK: - String-Convertible TestValues

private enum RawRepresentableStringTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> MockStringEnum {
        MockStringEnum.allCases.randomElement(using: &generator)!
    }


    static func different(from value: MockStringEnum, using generator: inout some RandomNumberGenerator) -> MockStringEnum {
        var result: MockStringEnum
        repeat {
            result = random(using: &generator)
        } while result == value
        return result
    }


    static func configContent(for value: MockStringEnum) -> ConfigContent {
        .string(value.rawValue)
    }
}


private enum RawRepresentableStringArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [MockStringEnum] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) { MockStringEnum.allCases.randomElement(using: &generator)! }
    }


    static func different(from value: [MockStringEnum], using generator: inout some RandomNumberGenerator) -> [MockStringEnum] {
        value + random(using: &generator)
    }


    static func configContent(for value: [MockStringEnum]) -> ConfigContent {
        .stringArray(value.map(\.rawValue))
    }
}


private enum ExpressibleByConfigStringTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> MockConfigStringValue {
        let count = Int.random(in: 5 ... 20, using: &generator)
        let string = String.randomAlphanumeric(count: count, using: &generator)
        return MockConfigStringValue(configString: string)!
    }


    static func different(from value: MockConfigStringValue, using generator: inout some RandomNumberGenerator) -> MockConfigStringValue {
        let suffix = random(using: &generator)
        return MockConfigStringValue(configString: value.stringValue + suffix.stringValue)!
    }


    static func configContent(for value: MockConfigStringValue) -> ConfigContent {
        .string(value.description)
    }
}


private enum ExpressibleByConfigStringArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [MockConfigStringValue] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) {
            let length = Int.random(in: 5 ... 20, using: &generator)
            return MockConfigStringValue(configString: String.randomAlphanumeric(count: length, using: &generator))!
        }
    }


    static func different(from value: [MockConfigStringValue], using generator: inout some RandomNumberGenerator) -> [MockConfigStringValue] {
        value + random(using: &generator)
    }


    static func configContent(for value: [MockConfigStringValue]) -> ConfigContent {
        .stringArray(value.map(\.description))
    }
}



// MARK: - MockIntEnum

private enum MockIntEnum: Int, CaseIterable, Sendable {
    case one = 1
    case two = 2
    case three = 3
    case four = 4
}


// MARK: - MockConfigIntValue

private struct MockConfigIntValue: ExpressibleByConfigInt, Hashable, Sendable {
    let intValue: Int

    var configInt: Int { intValue }

    var description: String { "\(intValue)" }

    init?(configInt: Int) {
        self.intValue = configInt
    }
}


// MARK: - Int-Convertible TestValues

private enum RawRepresentableIntTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> MockIntEnum {
        MockIntEnum.allCases.randomElement(using: &generator)!
    }


    static func different(from value: MockIntEnum, using generator: inout some RandomNumberGenerator) -> MockIntEnum {
        var result: MockIntEnum
        repeat {
            result = random(using: &generator)
        } while result == value
        return result
    }


    static func configContent(for value: MockIntEnum) -> ConfigContent {
        .int(value.rawValue)
    }
}


private enum RawRepresentableIntArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [MockIntEnum] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) { MockIntEnum.allCases.randomElement(using: &generator)! }
    }


    static func different(from value: [MockIntEnum], using generator: inout some RandomNumberGenerator) -> [MockIntEnum] {
        value + random(using: &generator)
    }


    static func configContent(for value: [MockIntEnum]) -> ConfigContent {
        .intArray(value.map(\.rawValue))
    }
}


private enum ExpressibleByConfigIntTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> MockConfigIntValue {
        MockConfigIntValue(configInt: Int.random(in: 1 ... 100_000, using: &generator))!
    }


    static func different(from value: MockConfigIntValue, using generator: inout some RandomNumberGenerator) -> MockConfigIntValue {
        MockConfigIntValue(configInt: value.intValue + random(using: &generator).intValue)!
    }


    static func configContent(for value: MockConfigIntValue) -> ConfigContent {
        .int(value.configInt)
    }
}


private enum ExpressibleByConfigIntArrayTestValues {
    static func random(using generator: inout some RandomNumberGenerator) -> [MockConfigIntValue] {
        let count = Int.random(in: 1 ... 5, using: &generator)
        return Array(count: count) {
            MockConfigIntValue(configInt: Int.random(in: 1 ... 100_000, using: &generator))!
        }
    }


    static func different(from value: [MockConfigIntValue], using generator: inout some RandomNumberGenerator) -> [MockConfigIntValue] {
        value + random(using: &generator)
    }


    static func configContent(for value: [MockConfigIntValue]) -> ConfigContent {
        .intArray(value.map(\.configInt))
    }
}


