//
//  ConfigVariableReader+Functions.swift
//  DevConfiguration
//
//  Generated using gyb.
//

// swift-format-ignore-file
//
// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################

import Configuration

// MARK: - Get

extension ConfigVariableReader {
    /// Gets the value for the specified `Bool` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<Bool>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Bool {
        return reader.bool(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[Bool]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<[Bool]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Bool] {
        return reader.boolArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `Float64` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<Float64>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Float64 {
        return reader.double(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[Float64]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<[Float64]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Float64] {
        return reader.doubleArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `Int` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<Int>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Int {
        return reader.int(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[Int]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<[Int]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Int] {
        return reader.intArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `String` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<String>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> String {
        return reader.string(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[String]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<[String]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [String] {
        return reader.stringArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[UInt8]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<[UInt8]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [UInt8] {
        return reader.bytes(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[[UInt8]]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value(
        for variable: ConfigVariable<[[UInt8]]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [[UInt8]] {
        return reader.byteChunkArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `RawRepresentable<String>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: RawRepresentable<String> {
        return reader.string(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[RawRepresentable<String>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: RawRepresentable<String> {
        return reader.stringArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `ExpressibleByConfigString` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: ExpressibleByConfigString {
        return reader.string(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[ExpressibleByConfigString]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: ExpressibleByConfigString {
        return reader.stringArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `RawRepresentable<Int>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: RawRepresentable<Int> {
        return reader.int(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[RawRepresentable<Int>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: RawRepresentable<Int> {
        return reader.intArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `ExpressibleByConfigInt` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: ExpressibleByConfigInt {
        return reader.int(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Gets the value for the specified `[ExpressibleByConfigInt]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func value<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: ExpressibleByConfigInt {
        return reader.intArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }
}


// MARK: - Subscript Get

extension ConfigVariableReader {
    /// Gets the value for the specified `Bool` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<Bool>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Bool {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[Bool]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<[Bool]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Bool] {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `Float64` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<Float64>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Float64 {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[Float64]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<[Float64]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Float64] {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `Int` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<Int>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Int {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[Int]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<[Int]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Int] {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `String` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<String>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> String {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[String]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<[String]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [String] {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[UInt8]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<[UInt8]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [UInt8] {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[[UInt8]]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript(
        variable: ConfigVariable<[[UInt8]]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [[UInt8]] {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `RawRepresentable<String>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Value>(
        variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: RawRepresentable<String> {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[RawRepresentable<String>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Element>(
        variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: RawRepresentable<String> {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `ExpressibleByConfigString` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Value>(
        variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: ExpressibleByConfigString {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[ExpressibleByConfigString]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Element>(
        variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: ExpressibleByConfigString {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `RawRepresentable<Int>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Value>(
        variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: RawRepresentable<Int> {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[RawRepresentable<Int>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Element>(
        variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: RawRepresentable<Int> {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `ExpressibleByConfigInt` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Value>(
        variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value
    where Value: ExpressibleByConfigInt {
        value(for: variable, fileID: fileID, line: line)
    }


    /// Gets the value for the specified `[ExpressibleByConfigInt]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to get a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public subscript<Element>(
        variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Element]
    where Element: ExpressibleByConfigInt {
        value(for: variable, fileID: fileID, line: line)
    }
}


// MARK: - Fetch

extension ConfigVariableReader {
    /// Asynchronously fetches the value for the specified `Bool` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<Bool>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> Bool {
        return try await reader.fetchBool(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[Bool]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<[Bool]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [Bool] {
        return try await reader.fetchBoolArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `Float64` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<Float64>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> Float64 {
        return try await reader.fetchDouble(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[Float64]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<[Float64]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [Float64] {
        return try await reader.fetchDoubleArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `Int` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<Int>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> Int {
        return try await reader.fetchInt(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[Int]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<[Int]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [Int] {
        return try await reader.fetchIntArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `String` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<String>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> String {
        return try await reader.fetchString(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[String]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<[String]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [String] {
        return try await reader.fetchStringArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[UInt8]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<[UInt8]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [UInt8] {
        return try await reader.fetchBytes(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[[UInt8]]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue(
        for variable: ConfigVariable<[[UInt8]]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [[UInt8]] {
        return try await reader.fetchByteChunkArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `RawRepresentable<String>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> Value
    where Value: RawRepresentable<String> {
        return try await reader.fetchString(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[RawRepresentable<String>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [Element]
    where Element: RawRepresentable<String> {
        return try await reader.fetchStringArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `ExpressibleByConfigString` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> Value
    where Value: ExpressibleByConfigString {
        return try await reader.fetchString(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[ExpressibleByConfigString]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [Element]
    where Element: ExpressibleByConfigString {
        return try await reader.fetchStringArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `RawRepresentable<Int>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> Value
    where Value: RawRepresentable<Int> {
        return try await reader.fetchInt(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[RawRepresentable<Int>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [Element]
    where Element: RawRepresentable<Int> {
        return try await reader.fetchIntArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `ExpressibleByConfigInt` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Value>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> Value
    where Value: ExpressibleByConfigInt {
        return try await reader.fetchInt(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }


    /// Asynchronously fetches the value for the specified `[ExpressibleByConfigInt]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to fetch a value for.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    /// - Returns: The configuration value of the variable, or the default value if resolution fails.
    public func fetchValue<Element>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line
    ) async throws -> [Element]
    where Element: ExpressibleByConfigInt {
        return try await reader.fetchIntArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line
        )
    }
}


// MARK: - Watch

extension ConfigVariableReader {
    /// Watches for updates to the value for the specified `Bool` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<Bool>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<Bool, Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchBool(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[Bool]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<[Bool]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[Bool], Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchBoolArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `Float64` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<Float64>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<Float64, Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchDouble(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[Float64]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<[Float64]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[Float64], Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchDoubleArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `Int` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<Int>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<Int, Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchInt(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[Int]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<[Int]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[Int], Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchIntArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `String` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<String>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<String, Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchString(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[String]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<[String]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[String], Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchStringArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[UInt8]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<[UInt8]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[UInt8], Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchBytes(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[[UInt8]]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Return>(
        for variable: ConfigVariable<[[UInt8]]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[[UInt8]], Never>) async throws -> Return
    ) async throws -> Return
    where Return: ~Copyable {
        try await reader.watchByteChunkArray(
            forKey: variable.key,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `RawRepresentable<String>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Value, Return>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<Value, Never>) async throws -> Return
    ) async throws -> Return
    where Value: RawRepresentable<String> & Sendable {
        try await reader.watchString(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[RawRepresentable<String>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Element, Return>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[Element], Never>) async throws -> Return
    ) async throws -> Return
    where Element: RawRepresentable<String> & Sendable {
        try await reader.watchStringArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `ExpressibleByConfigString` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Value, Return>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<Value, Never>) async throws -> Return
    ) async throws -> Return
    where Value: ExpressibleByConfigString & Sendable {
        try await reader.watchString(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[ExpressibleByConfigString]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Element, Return>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[Element], Never>) async throws -> Return
    ) async throws -> Return
    where Element: ExpressibleByConfigString & Sendable {
        try await reader.watchStringArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `RawRepresentable<Int>` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Value, Return>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<Value, Never>) async throws -> Return
    ) async throws -> Return
    where Value: RawRepresentable<Int> & Sendable {
        try await reader.watchInt(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[RawRepresentable<Int>]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Element, Return>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[Element], Never>) async throws -> Return
    ) async throws -> Return
    where Element: RawRepresentable<Int> & Sendable {
        try await reader.watchIntArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `ExpressibleByConfigInt` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Value, Return>(
        for variable: ConfigVariable<Value>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<Value, Never>) async throws -> Return
    ) async throws -> Return
    where Value: ExpressibleByConfigInt & Sendable {
        try await reader.watchInt(
            forKey: variable.key,
            as: Value.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }


    /// Watches for updates to the value for the specified `[ExpressibleByConfigInt]` config variable.
    ///
    /// - Parameters:
    ///   - variable: The variable to watch for updates.
    ///   - fileID: The source file identifier for access reporting.
    ///   - line: The source line number for access reporting.
    ///   - updatesHandler: A closure that handles an async sequence of updates to the value.
    /// - Returns: The result produced by the handler.
    public func watchValue<Element, Return>(
        for variable: ConfigVariable<[Element]>,
        fileID: String = #fileID,
        line: UInt = #line,
        updatesHandler: (_ updates: ConfigUpdatesAsyncSequence<[Element], Never>) async throws -> Return
    ) async throws -> Return
    where Element: ExpressibleByConfigInt & Sendable {
        try await reader.watchIntArray(
            forKey: variable.key,
            as: Element.self,
            isSecret: isSecret(variable),
            default: variable.defaultValue,
            fileID: fileID,
            line: line,
            updatesHandler: updatesHandler
        )
    }
}
